name: cctv_sasat
description: project pantauan cctv by satria ramadan.
publish_to: none
version: 1.0.1

environment:
  sdk: ^3.6.1

dependencies:
  flutter:
    sdk: flutter

  base:
    git:
      url: https://github.com/strhmdn14102004/assets-flutter.git
      # path: D:/assets
  flutter_bloc: ^9.1.1
  go_router: ^16.0.0
  provider: ^6.1.5
  loader_overlay: ^2.1.0
  package_info_plus: ^8.3.0
  webview_flutter: ^4.13.0
  shimmer: 3.0.0
  equatable: 2.0.7
  cached_network_image: ^3.4.1
  url_launcher: ^6.3.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/font/
    - assets/image/
    - assets/lottie/
    - assets/i18n/
  fonts:
    - family: Manrope
      fonts:
        - asset: assets/font/Manrope-Bold.ttf
        - asset: assets/font/Manrope-ExtraBold.ttf
        - asset: assets/font/Manrope-ExtraLight.ttf
        - asset: assets/font/Manrope-Light.ttf
        - asset: assets/font/Manrope-Medium.ttf
        - asset: assets/font/Manrope-Regular.ttf
        - asset: assets/font/Manrope-SemiBold.ttf
